config/routes.rb
T1::Application.routes.draw do
  resources :evaluation_sessions, only: [:new, :create, :index, :show] do
    resources :criteria, only: [:new, :create, :index, :show]
  end
  resources :items, only: [:new, :create, :index, :show] do
    resources :ratings, only: [:new, :create, :index]
  end

end

app/models/criterion.rb
class Criterion < ActiveRecord::Base
  belongs_to :evaluation_session
  has_many :ratings
  validates :name, presence: true, uniqueness: {scope: :evaluation_session_id}
end

app/models/evaluation_session.rb
class EvaluationSession < ActiveRecord::Base
  has_many :items, dependent: :destroy
  has_many :criteria, dependent: :destroy
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :item_type, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :evaluation_session
  has_many :ratings
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :criterion
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/criteria_controller.rb
class CriteriaController < ApplicationController
  def new
    @evaluation_session = EvaluationSession.find(params[:evaluation_session_id])
    @criterion = @evaluation_session.criteria.build
  end

  def index
    @evaluation_session = EvaluationSession.find(params[:evaluation_session_id]).include([:criteria])
    @criteria = @evaluation_session.criteria
  end

  def create
    @evaluation_session = EvaluationSession.find(params[:evaluation_session_id])
    @criterion = @evaluation_session.criteria.build(criterion_params)
      if @criterion.save
        redirect_to new_evaluation_session_criterion_path
        flash[:notice] = "Criterion created."
      else
        render 'new'
      end
  end

  private
    def criterion_params
      params.require(:criterion).permit(:name, :description, :rank_among_criteria).merge(evaluation_session_id: params[:evaluation_session_id])
    end
  end

app/controllers/evaluation_sessions_controller.rb
class EvaluationSessionsController < ApplicationController
  def new
    @evaluation_session = EvaluationSession.new
  end

  def index
    @evaluation_sessions = EvaluationSession.all
  end

  def create
    @evaluation_session = EvaluationSession.new(evaluation_session_params)
      if @evaluation_session.save
        redirect_to evaluation_sessions_path
        flash[:notice] = "Evaluation session created."
      else
        render 'new'
        flash[:notice] = "Evaluation session not created. Please correct errors."
      end
  end

  def show
    @evaluation_session = EvaluationSession.find(params[:id])
    @criterion = Criterion.new
    @item = Item.new
    @criteria = @evaluation_session.criteria
    @items = @evaluation_session.items
  end

  private
    def evaluation_session_params
      params.require(:evaluation_session).permit(:name, :description, :item_type)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def create
    @item = Item.new(item_params)
      if @item.save
        redirect_to new_item_path
        flash[:notice] = "Item created."
      else
        render 'new'
        flash[:notice] = "Item not created. Please correct errors."
      end

  end

    def show
    @item = Item.find(params[:id])
    @rating = Rating.new
    @rating = @item.rating
    @ratings = @item.ratings
  end

  private
    def item_params
      params.require(:item).permit(:name, :description)
    end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    @item = Item.find(params[:item_id])
    @rating = @item.ratings.build
  end

  def index
    @item = Item.find(params[:item_id]).include([:ratings])
    @ratings = @item.ratings
  end

  def create
    @item = Item.find(params[:item_id])
    @rating = @item.ratings.build(rating_params)
      if @rating.save
        redirect_to new_item_rating_path
        flash[:notice] = "Rating created."
      else
        render 'new'
      end
  end

  private
    def rating_params
      params.require(:rating).permit(:grouping, :rank, :score).merge(item_id: params[:item_id])
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/criteria/new.html.erb
<%= simple_form_for [@evaluation_session, @criterion] do |c| %>
  <%= c.input :name %>
  <%= c.input :description %>
  <%= c.button :submit %>
<% end %>

app/views/evaluation_sessions/index.html.erb
<h1> Evaluation Sessions </h1>
<table>
  <thead>
    <tr>
      <th> Name </th>
      <th> Description </th>
      <th> Item type </th>
    </tr>
  </thead>

  <tbody>
    <% @evaluation_sessions.each do |es| %>
    <tr>
      <td><%= link_to es.name, evaluation_session_path(es) %></td>
      <td><%= es.description %> </td>
      <td><%= es.item_type %> </td>
    </tr>
    <br>
    <% end %>
  </tbody>
</table>

<%= link_to "Create new evaluation session", new_evaluation_session_path, class: 'button' %>

app/views/evaluation_sessions/new.html.erb
<%= simple_form_for @evaluation_session do |e| %>
  <%= e.input :name %>
  <%= e.input :description %>
  <%= e.input :item_type %>
  <%= e.submit %>
<% end %>

app/views/evaluation_sessions/show.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Item type</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @evaluation_session.name %></td>
      <td><%= @evaluation_session.description %></td>
      <td><%= @evaluation_session.item_type %></td>
    </tr>
  </tbody>
</table>
<% # if this evaluation_session has criteria associated with it, display the following table %>
<table>
  <thead>
    <tr>
      <th> <%= @evaluation_session.item_type %> </th>
      <% @criteria.each do |criterion| %>
        <th><%= criterion.name %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <% @criteria.each do |criteria| %>
        <td>
          <%= simple_form_for [item, item.ratings.build] do |f| %>
            <%= f.association :criterion, as: :hidden, value: item %>
            <%= f.input :grouping %>
            <%= f.button :submit %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "Add criterion", new_evaluation_session_criterion_path(@evaluation_session), class: 'button' %>

app/views/items/new.html.erb
<%= simple_form_for @item do |item| %>
<% evaluation_session.items.each do |item| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.submit %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>

    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>